[project]
name = "ether"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyzmq>=26.2.0",
    "pydantic>=2.9.2",
    "psutil>=6.1.0",
    "sqlalchemy>=2.0.36",
    "redis>=5.2.0",
    "pytest>=8.3.3",
    "pyyaml>=6.0.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
